server:
  port: ${PORT:8080} # Railway asigna el puerto dinámicamente

spring:
  cloud:
    gateway:
      routes:
        - id: libros-service
          # Busca la variable LIBROS_SERVICE_URL; si no existe, usa localhost
          uri: ${LIBROS_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/libros/**
          filters:
            - StripPrefix=2          
            
            